name: Deploy to Coolify

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        run: |
          curl -sf -X POST \
            --max-time 15 \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            "http://191.215.40.162:8000/api/v1/deploy?uuid=xdhjngsphjmefhpcluf9ufqu&force=false"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        run: |
          curl -sf -X POST \
            --max-time 15 \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            "http://191.215.40.162:8000/api/v1/deploy?uuid=lw788hbjjoj6og94zrcswjcf&force=false"
